services:
  - type: web
    name: veltrix-ai
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PAYPAL_WEBHOOK_ID
        sync: false
      - key: ULTRAMSG_INSTANCE_ID
        sync: false
      - key: ULTRAMSG_TOKEN
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
